version: '2.2'

services:
  db:
    build: dockerfiles/db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: webout
      POSTGRES_PASS: webout
      POSTGRES_ADDR: db:5432
      POSTGRES_DB: webout
    volumes:
      - ./dockerfiles/db/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./postgresql/data:/var/lib/postgresql/data

  webout:
    build: ./
    depends_on:
      - db
    ports:
      - 8989:8989
    volumes:
      - $GOPATH/src/github.com/gillchristian/webout:/go/src/github.com/gillchristian/webout
